### ISSUE TITLE
Gitlab Clone Link HTTP 

### ISSUE THREAD

**Issue by murphyj21** [plus3it/cfn-gitlab#1]
### Problem Description:

The download links for projects is showing up as `HTTP` instead of `HTTPS`. 

If you copy the link and try to clone a repo it'll fail until you change `http://` to `https://`.

**Comment by ferricoxide** [comment]
@murphyj21 When I recovered GitLab, this morning, the clone-URL was showing HTTPS. Can you validate that this is an issue that's still open?

**Comment by murphyj21** [comment]
It appears to be resolved. Not sure what config change was made to cause the issue in the first place. Closing.
